export const MOCK_BLOGS = [
  {
    _id: "1",
    title: "Getting Started with Next.js",
    slug: "getting-started-with-nextjs",
    excerpt: "Learn how to build modern web applications with Next.js, the React framework for production.",
    content: "Next.js gives you the best developer experience with all the features you need for production...",
    coverImage: "/placeholder.svg?height=400&width=600",
    author: {
      name: "John Doe",
      image: "/placeholder.svg?height=100&width=100",
    },
    createdAt: "2023-05-15T10:00:00Z",
    tags: ["Next.js", "React", "Web Development"],
  },
  {
    _id: "2",
    title: "Mastering Three.js for Interactive Web Experiences",
    slug: "mastering-threejs-for-interactive-web",
    excerpt: "Discover how to create immersive 3D experiences on the web using Three.js.",
    content: "Three.js is a powerful JavaScript library that makes it easy to create 3D graphics in the browser...",
    coverImage: "/placeholder.svg?height=400&width=600",
    author: {
      name: "John Doe",
      image: "/placeholder.svg?height=100&width=100",
    },
    createdAt: "2023-06-22T14:30:00Z",
    tags: ["Three.js", "3D", "JavaScript", "WebGL"],
  },
  {
    _id: "3",
    title: "Building a Full-Stack App with Next.js and MongoDB",
    slug: "building-fullstack-app-nextjs-mongodb",
    excerpt: "A comprehensive guide to creating a complete web application with Next.js and MongoDB.",
    content: "In this tutorial, we'll walk through the process of building a full-stack application...",
    coverImage: "/placeholder.svg?height=400&width=600",
    author: {
      name: "John Doe",
      image: "/placeholder.svg?height=100&width=100",
    },
    createdAt: "2023-07-10T09:15:00Z",
    tags: ["Next.js", "MongoDB", "Full-Stack", "Web Development"],
  },
  {
    _id: "4",
    title: "Responsive Design Principles for Modern Websites",
    slug: "responsive-design-principles-modern-websites",
    excerpt: "Learn the key principles of responsive design to create websites that work on any device.",
    content: "Responsive design is more important than ever in today's multi-device world...",
    coverImage: "/placeholder.svg?height=400&width=600",
    author: {
      name: "John Doe",
      image: "/placeholder.svg?height=100&width=100",
    },
    createdAt: "2023-08-05T16:45:00Z",
    tags: ["CSS", "Responsive Design", "Web Development"],
  },
  {
    _id: "5",
    title: "Optimizing Performance in React Applications",
    slug: "optimizing-performance-react-applications",
    excerpt: "Strategies and techniques to improve the performance of your React applications.",
    content: "Performance optimization is crucial for providing a good user experience...",
    coverImage: "/placeholder.svg?height=400&width=600",
    author: {
      name: "John Doe",
      image: "/placeholder.svg?height=100&width=100",
    },
    createdAt: "2023-09-18T11:20:00Z",
    tags: ["React", "Performance", "JavaScript", "Optimization"],
  },
  {
    _id: "6",
    title: "Introduction to Framer Motion for React Animations",
    slug: "introduction-framer-motion-react-animations",
    excerpt: "Learn how to add beautiful animations to your React applications with Framer Motion.",
    content: "Framer Motion is a production-ready motion library for React that makes it easy to create animations...",
    coverImage: "/placeholder.svg?height=400&width=600",
    author: {
      name: "John Doe",
      image: "/placeholder.svg?height=100&width=100",
    },
    createdAt: "2023-10-30T13:10:00Z",
    tags: ["React", "Animation", "Framer Motion", "UI/UX"],
  },
  {
    _id: "7",
    title: "The Future of Web Development: What's Coming in 2024",
    slug: "future-web-development-2024",
    excerpt: "Explore the upcoming trends and technologies that will shape web development in 2024.",
    content: "The web development landscape is constantly evolving. Let's look at what's on the horizon...",
    coverImage: "/placeholder.svg?height=400&width=600",
    author: {
      name: "John Doe",
      image: "/placeholder.svg?height=100&width=100",
    },
    createdAt: "2023-12-12T08:30:00Z",
    tags: ["Web Development", "Trends", "Future Tech"],
  },
  {
    _id: "8",
    title: "Creating Accessible Web Applications",
    slug: "creating-accessible-web-applications",
    excerpt: "Best practices for building web applications that are accessible to all users.",
    content: "Web accessibility is not just a nice-to-have feature, it's a necessity...",
    coverImage: "/placeholder.svg?height=400&width=600",
    author: {
      name: "John Doe",
      image: "/placeholder.svg?height=100&width=100",
    },
    createdAt: "2024-01-25T15:40:00Z",
    tags: ["Accessibility", "Web Development", "Inclusive Design"],
  },
]
